---

- name: Install Update CRON
  template:
    src="ceph-mirror.j2"
    dest="{{ mirror_cron_dir }}/ceph-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="Ceph"
    minute="{{ 59 | random(seed=inventory_hostname) }}"
    hour="{{ 23 | random(seed=inventory_hostname) }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/ceph-mirror -q -s {{ ceph_download_region }} -t {{ mirror_doc_root }}/ceph"
    disabled="{{ ceph_mirror_cron_disabled }}"
