---

- name: Install Update CRON
  template:
    src="ceph-mirror.j2"
    dest="{{ mirror_cron_dir }}/ceph-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="Ceph"
    minute="{{ ceph_mirror_cron_minute }}"
    hour="{{ ceph_mirror_cron_hour }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/ceph-mirror -q -s {{ ceph_download_region }} -t {{ mirror_doc_root }}/ceph >/dev/null 2>&1"
    disabled="{{ ceph_mirror_cron_disabled }}"

- stat:
    path="{{ mirror_timestamp_dir }}/ceph"
  register: tsfile

- name: Seed Timestamp File
  copy:
    content="0"
    dest="{{ mirror_timestamp_dir }}/ceph"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0644
  when: not tsfile.stat.exists
